In [ ]:
import pandas as pd

tabela = pd.read_csv("C:\Formação Python Developer\Forma--o-Python-Developer\hashtag impressionador\clientes.csv")
#display(tabela)
display(tabela.info())

In [ ]:
# converter tabelas de texto para numeros

#display(tabela)

import sklearn
from sklearn.preprocessing import LabelEncoder

codificador = LabelEncoder()
tabela["profissao"] = codificador.fit_transform(tabela["profissao"])
#display(tabela["profissao"])
codificador2 = LabelEncoder()
tabela["mix_credito"] = codificador2.fit_transform(tabela["mix_credito"])
codificador3 = LabelEncoder()
tabela["comportamento_pagamento"] = codificador3.fit_transform(tabela["comportamento_pagamento"])
display(tabela.info())

In [20]:
# y é quem eu quero preve
y = tabela["score_credito"] 
 # x é quem a IA vai usar para prever entao tiramos a tabela de estudo e tabela inuteis
x = tabela.drop(columns=["score_credito", "id_cliente"])


# funcao para dividir aleatoriamente para treino e para teste
from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(x,y)

In [39]:
#criar um modelo de IA


from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

# criando IA
modelo_arvoredecisao = RandomForestClassifier()
modelo_knn = KNeighborsClassifier()

#treinando IA

modelo_arvoredecisao.fit(x_treino, y_treino)
modelo_knn.fit(x_treino, y_treino)

# verificar qual melhor ia (acuracia)

previsao_arvoredecisao = modelo_arvoredecisao.predict(x_teste)
previsao_knn = modelo_knn.predict(x_teste)

from sklearn.metrics import accuracy_score

display(accuracy_score(y_teste,previsao_arvoredecisao ))
display(accuracy_score(y_teste, previsao_knn))

0.8292

0.74424

In [40]:
# cliente novo 
import pandas as pd
import sklearn
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier


tabela = pd.read_csv(r"C:\Formação Python Developer\Forma--o-Python-Developer\hashtag impressionador\novos_clientes.csv")
display(tabela)

codificador = LabelEncoder()
tabela["profissao"] = codificador.fit_transform(tabela["profissao"])
codificador2 = LabelEncoder()
tabela["mix_credito"] = codificador2.fit_transform(tabela["mix_credito"])
codificador3 = LabelEncoder()
tabela["comportamento_pagamento"] = codificador3.fit_transform(tabela["comportamento_pagamento"])

previsao_arvoredecisao = modelo_arvoredecisao.predict(tabela)

display(previsao_arvoredecisao)

,mes,idade,profissao,salario_anual,num_contas,num_cartoes,juros_emprestimo,num_emprestimos,dias_atraso,num_pagamentos_atrasados,...,taxa_uso_credito,idade_historico_credito,investimento_mensal,comportamento_pagamento,saldo_final_mes,emprestimo_carro,emprestimo_casa,emprestimo_pessoal,emprestimo_credito,emprestimo_estudantil
0,1,31.0,empresario,19300.340,6.0,7.0,17.0,5.0,52.0,19.0,...,29.934186,218.0,44.50951,baixo_gasto_pagamento_baixo,312.487689,1,1,0,0,0
1,4,32.0,advogado,12600.445,5.0,5.0,10.0,3.0,25.0,18.0,...,28.819407,12.0,0.00000,baixo_gasto_pagamento_medio,300.994163,0,0,0,0,1
2,2,48.0,empresario,20787.690,8.0,6.0,14.0,7.0,24.0,14.0,...,34.235853,215.0,0.00000,baixo_gasto_pagamento_alto,345.081577,0,1,0,1,0

array(['Poor', 'Good', 'Standard'], dtype=object)